# Generated by Django 4.2.18 on 2025-02-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_subject_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='api.subject'),
        ),
    ]
