# Generated by Django 4.2.18 on 2025-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='numHours',
            field=models.IntegerField(default=18),
        ),
    ]
